import { test } from "node:test";
import assert from "node:assert/strict";
import { findStale, regenerateSdkTypes } from "./check-contract-fresh.ts";

test("findStale reports nothing when committed content matches fresh content", () => {
  const stale = findStale([{ label: "x", committedPath: "/fake/x", freshContent: "same" }], () => "same");
  assert.deepEqual(stale, []);
});

test("findStale reports drift when committed content differs from fresh content", () => {
  const stale = findStale(
    [{ label: "contract/openapi.json", committedPath: "/fake/openapi.json", freshContent: "new" }],
    () => "old",
  );
  assert.deepEqual(stale, ["contract/openapi.json: /fake/openapi.json is stale — run `npm run contract:gen && npm run sdk:gen` and commit the result"]);
});

test("findStale reports a missing committed file distinctly from drift", () => {
  const stale = findStale([{ label: "x", committedPath: "/fake/missing", freshContent: "anything" }], () => {
    throw Object.assign(new Error("ENOENT"), { code: "ENOENT" });
  });
  assert.deepEqual(stale, ["x: /fake/missing does not exist — run `npm run contract:gen && npm run sdk:gen` and commit the result"]);
});

test("findStale checks every entry, not just the first", () => {
  const stale = findStale(
    [
      { label: "a", committedPath: "/fake/a", freshContent: "fresh-a" },
      { label: "b", committedPath: "/fake/b", freshContent: "fresh-b" },
    ],
    (path) => (path === "/fake/a" ? "fresh-a" : "stale-b"),
  );
  assert.deepEqual(stale, ["b: /fake/b is stale — run `npm run contract:gen && npm run sdk:gen` and commit the result"]);
});

/* Exercises the real openapi-typescript CLI end-to-end (the actual shell-out this script relies
   on) against a minimal synthetic schema — isolated from the production contract so this test
   doesn't churn every time the real schema changes.
 */
test("regenerateSdkTypes runs the real generator end-to-end on a minimal schema", () => {
  const doc = {
    openapi: "3.0.3",
    info: { title: "fixture", version: "1.0.0" },
    paths: {},
    components: {
      schemas: {
        Widget: { type: "object", properties: { id: { type: "string" } }, required: ["id"] },
      },
    },
  };
  const out = regenerateSdkTypes(JSON.stringify(doc));
  assert.match(out, /auto-generated by openapi-typescript/);
  assert.match(out, /Widget/);
});
